#!/usr/bin/env python3
"""Run seed-paired SH-MPCC/DRO comparisons under configured plant shifts."""
import argparse
import concurrent.futures
import json
import math
from pathlib import Path
import re
import sys

import run_analysis_matrix as analysis

ROOT = analysis.ROOT
PAIR_STYLES = ('sh_mpcc', 'sh_mpcc_dro')
SHIFT_KEYS = {'shift_psi', 'shift_boost', 'boosted_mode', 'rare_mode', 'rare_mode_probability'}


def load_settings(path):
    settings = analysis.load_settings(path)
    if settings['solver_styles'] != list(PAIR_STYLES):
        raise ValueError('comparison matrix requires sh_mpcc and sh_mpcc_dro in that order')
    if SHIFT_KEYS.union({'shift_rho'}).intersection(settings.get('overrides', {})):
        raise ValueError('put shift/rare-mode options in mismatch_profiles, not overrides')
    profiles = settings['mismatch_profiles']
    names = set()
    for profile in profiles:
        name = profile['name']
        if not re.fullmatch(r'[a-z][a-z0-9_]*', name) or name in names:
            raise ValueError('profile names must be unique lowercase identifiers')
        names.add(name)
        if set(profile) - SHIFT_KEYS - {'name'}:
            raise ValueError(f'unknown profile keys: {name}')
        for key in ('shift_psi', 'shift_boost', 'rare_mode_probability'):
            value = profile.get(key, 0)
            if type(value) not in (int, float) or not math.isfinite(value) or not 0 <= value <= 1:
                raise ValueError(f'{name}: {key} must be a probability in [0, 1]')
        boosted = profile.get('boosted_mode', -1)
        if type(boosted) is not int or not -1 <= boosted < min(settings['mode_counts']):
            raise ValueError(f'{name}: boosted_mode is outside a configured mode support')
        rare = profile.get('rare_mode', '')
        if rare and rare not in settings['mode_catalog'][:min(settings['mode_counts'])]:
            raise ValueError(f'{name}: rare_mode must be present in every configured support')
        if profile.get('rare_mode_probability', 0) > 0 and not rare:
            raise ValueError(f'{name}: rare_mode_probability requires rare_mode')
    if not profiles:
        raise ValueError('mismatch_profiles must not be empty')
    return settings


def configurations(settings):
    for profile in settings['mismatch_profiles']:
        for case in analysis.configurations(settings):
            pair = f"{case['environment']}_o{case['obstacles']}_c{case['classes']}_m{case['modes_per_class']}_{profile['name']}"
            yield {**case, 'case': f"{case['solver_style']}_{pair}",
                   'pair': pair, 'pair_directory': pair, 'profile': profile['name']}


def config_text(case, settings):
    profile = next(p for p in settings['mismatch_profiles'] if p['name'] == case['profile'])
    values = dict(shift_psi=0.0, shift_boost=0.0, boosted_mode=-1,
                  rare_mode='', rare_mode_probability=0.0)
    values.update({k: v for k, v in profile.items() if k != 'name'})
    # Replace only existing flat YAML keys; the shared generator preserves all defaults.
    lines = analysis.config_text(case, settings).splitlines()
    for i, line in enumerate(lines):
        key = line.split(':', 1)[0]
        if key in values:
            lines[i] = f'{key}: {json.dumps(values[key])}'
    lines[0] = '# Generated by run_comparison_matrix.py; paired plant settings.'
    return '\n'.join(lines) + '\n'


def obstacle_prefix_matches(a, b):
    def obstacles(bundle):
        return {(int(r['step']), r['obstacle_id']):
                tuple(r[k] for k in ('mode', 'x', 'y', 'vx', 'vy'))
                for r in analysis.rows(bundle/'trace.csv') if r['actor'] == 'obstacle'}
    left, right = obstacles(a), obstacles(b)
    if not left or not right:
        return False
    end = min(max(k[0] for k in left), max(k[0] for k in right))
    return {k: v for k, v in left.items() if k[0] <= end} == {
        k: v for k, v in right.items() if k[0] <= end}


def paired_result(cases, seed, results, output):
    row = {k: cases[0][k] for k in ('pair', 'profile', 'environment', 'obstacles', 'classes', 'modes_per_class')}
    row.update(seed=seed, status='PENDING', target_match=False, reverse_match=False)
    trials = [results.get((c['case'], seed)) for c in cases]
    for label, case, trial in zip(('nondro', 'dro'), cases, trials):
        row[f'{label}_artifact'] = str(analysis.trial_root(output, case, seed)/'repeat_0')
        row[f'{label}_status'] = trial['status'] if trial else 'PENDING'
        row[f'{label}_error'] = trial.get('error', '') if trial else ''
        if trial and trial['status'] == 'OK':
            row.update({f'{label}_{k}': v for k, v in trial['repeats'][0]['metrics'].items()
                        if k != 'initial_placement'})
    if any(t and t['status'] != 'OK' for t in trials):
        row['status'] = 'ERROR'
        return row
    if any(t is None for t in trials):
        return row
    try:
        a, b = trials
        if len(a['repeats']) != len(b['repeats']):
            raise ValueError('repeat counts differ')
        for repeat, (left, right) in enumerate(zip(a['repeats'], b['repeats'])):
            for field in ('plant_seed', 'controller_seed', 'initial_placement', 'backend', 'solver_identity'):
                if left['metrics'][field] != right['metrics'][field]:
                    raise ValueError(f'paired {field} mismatch')
            bundles = [analysis.trial_root(output, c, seed)/f'repeat_{repeat}' for c in cases]
            if not obstacle_prefix_matches(*bundles):
                raise ValueError('paired obstacle trajectories differ over shared steps')
        row['status'] = 'OK'
        row['paired_obstacle_prefix_equal'] = True
        row['nondro_safe_completion'] = bool(not row['nondro_collision'] and row['nondro_completed_path'])
        row['dro_safe_completion'] = bool(not row['dro_collision'] and row['dro_completed_path'])
        row['target_match'] = bool(row['nondro_collision'] and row['dro_safe_completion'])
        row['reverse_match'] = bool(row['dro_collision'] and row['nondro_safe_completion'])
        row['nondro_collision_dro_collision_free_incomplete'] = bool(
            row['nondro_collision'] and not row['dro_collision'] and not row['dro_completed_path'])
    except (OSError, ValueError, KeyError) as error:
        row.update(status='ERROR', error=str(error))
    return row


def summarize(pairs):
    summaries = []
    for name in sorted({r['pair'] for r in pairs}):
        group = [r for r in pairs if r['pair'] == name]
        good = [r for r in group if r['status'] == 'OK']
        row = {k: group[0][k] for k in ('pair', 'profile', 'environment', 'obstacles', 'classes', 'modes_per_class')}
        row.update(expected_pairs=len(group), measured_pairs=len(good),
                   error_pairs=sum(r['status'] == 'ERROR' for r in group),
                   pending_pairs=sum(r['status'] == 'PENDING' for r in group))
        for field in ('target_match', 'reverse_match', 'nondro_collision', 'dro_collision',
                      'nondro_safe_completion', 'dro_safe_completion',
                      'nondro_collision_dro_collision_free_incomplete'):
            count = sum(bool(r[field]) for r in good)
            row[field+'_count'] = count
            row[field+'_rate'] = count/len(good) if good else None
        row['target_seeds'] = ';'.join(str(r['seed']) for r in good if r['target_match'])
        summaries.append(row)
    return sorted(summaries, key=lambda r: (-r['target_match_count'], r['pair']))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--settings', type=Path, default=ROOT/'configs/comparison_matrix/settings.json')
    parser.add_argument('--runner', type=Path, default=ROOT/'build-base/experiment_runner')
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--case', help='Exact pair name; selects both controllers')
    parser.add_argument('--generate-only', action='store_true')
    parser.add_argument('--resume', action='store_true')
    parser.add_argument('--jobs', type=int, default=1)
    parser.add_argument('--timeout', type=float, default=1800)
    args = parser.parse_args(argv)
    if args.jobs < 1 or not math.isfinite(args.timeout) or args.timeout <= 0:
        parser.error('jobs and timeout must be positive and finite')
    args.output, args.runner = args.output.resolve(), args.runner.resolve()
    settings = load_settings(args.settings)
    cases = list(configurations(settings))
    selected = [c for c in cases if args.case is None or c['pair'] == args.case]
    if not selected:
        parser.error('no matching comparison cases')
    texts = {c['case']: config_text(c, settings) for c in cases}
    manifest = dict(schema=2, suite='comparison_matrix', settings=settings, cases=cases,
        configs={k: analysis.digest(v.encode()) for k, v in texts.items()},
        runner=str(args.runner), runner_sha256=analysis.digest(args.runner.read_bytes()),
        script_sha256=analysis.digest(Path(__file__).read_bytes()),
        analysis_sha256=analysis.digest(Path(analysis.__file__).read_bytes()),
        jobs=args.jobs, timeout=args.timeout)
    identity = analysis.digest(json.dumps(manifest, sort_keys=True).encode())
    manifest['identity'] = identity
    args.output.mkdir(parents=True, exist_ok=True)
    path = args.output/'matrix.json'
    if path.exists() and json.loads(path.read_text()) != manifest:
        parser.error('output contains a different manifest; use a new output directory')
    analysis.dump_json(path, manifest)
    (args.output/'configs').mkdir(exist_ok=True)
    for case in selected:
        (args.output/'configs'/(case['case']+'.yaml')).write_text(texts[case['case']])
    print(f'{len(selected)//2} comparison cases; '
          f'{len(selected)//2*len(settings["seeds"])} seed pairs; '
          f'{len(selected)*len(settings["seeds"])*settings["repeats"]} executions', flush=True)
    if args.generate_only:
        return 0
    results = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = [pool.submit(analysis.run_trial, c, seed, args, settings, identity)
                   for c in selected for seed in settings['seeds']]
        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            results[result['case'], result['seed']] = result
            print(f'{result["case"]} seed={result["seed"]}: {result["status"]}', flush=True)
    pairs = [paired_result([c for c in selected if c['pair'] == name], seed, results, args.output)
             for name in sorted({c['pair'] for c in selected}) for seed in settings['seeds']]
    analysis.dump_json(args.output/'results.json', sorted(results.values(), key=lambda r: (r['case'], r['seed'])))
    for name, data in (('pairs', pairs), ('matches', [r for r in pairs if r['target_match']]),
                       ('summary', summarize(pairs))):
        analysis.dump_json(args.output/(name+'.json'), data)
        analysis.write_csv(args.output/(name+'.csv'), data)
    print(f'{sum(r["target_match"] for r in pairs)} target matches; '
          f'{sum(r["status"] == "ERROR" for r in pairs)} pair errors', flush=True)
    return int(any(r['status'] != 'OK' for r in pairs))


if __name__ == '__main__':
    sys.exit(main())
