import DROSafety.DRO.BoxSimplexConvexHull
import Mathlib

set_option linter.style.header false
set_option linter.style.emptyLine false

/-!
# Geometry of the box-simplex vertex enumerator

The C++ calibration routine enumerates candidate vertices by:

1. choosing one coordinate `freeIndex`;
2. placing every other coordinate at either its lower or upper bound;
3. computing the free coordinate from the simplex equality

       q_free = 1 - sum_{i != free} q_i;

4. accepting the candidate when the free coordinate lies inside its interval.

The previous decomposition theorem showed that every point of the confidence
polytope lies in the convex hull of feasible points with at most one
strictly-free coordinate.

This file proves that, when the mode dimension is nonzero, those terminal
points are exactly points having the geometric form generated by the C++
enumerator.

Thus the remaining implementation-refinement step is only to connect the
actual recursive lower/upper branching routine to the abstract candidate
set defined here.
-/

namespace DROSafety.DRO

open scoped BigOperators

/--
A coordinate is on one of its interval endpoints.
-/
def OnIntervalEndpoint
    {d : ℕ}
    (lower upper : Fin d → ℝ)
    (q : ModeDistribution d)
    (i : Fin d) :
    Prop :=
  q i = lower i ∨
  q i = upper i

/--
A feasible coordinate that is not strictly interior must lie on one of the
two interval endpoints.
-/
theorem onIntervalEndpoint_of_not_strictlyFree
    {d : ℕ}
    {lower upper : Fin d → ℝ}
    {q : ModeDistribution d}
    {i : Fin d}
    (hq :
      q ∈ ConfidencePolytope
        lower
        upper)
    (hNotFree :
      ¬ StrictlyFree
        lower
        upper
        q
        i) :
    OnIntervalEndpoint
      lower
      upper
      q
      i := by

  have hLower :
      lower i ≤ q i :=
    (hq.2 i).1

  have hUpper :
      q i ≤ upper i :=
    (hq.2 i).2

  by_cases hEqLower :
      q i = lower i

  · exact Or.inl hEqLower

  · by_cases hEqUpper :
        q i = upper i

    · exact Or.inr hEqUpper

    · exfalso

      apply hNotFree

      constructor

      · exact
          lt_of_le_of_ne
            hLower
            (Ne.symm hEqLower)

      · exact
          lt_of_le_of_ne
            hUpper
            hEqUpper

/--
For any probability vector, one coordinate is determined by all the others
through the simplex equality.
-/
theorem probabilityVector_freeCoordinate_eq
    {d : ℕ}
    {q : ModeDistribution d}
    (hq :
      IsProbabilityVector q)
    (freeIndex : Fin d) :
    q freeIndex
      =
    1 -
      Finset.sum
        (Finset.univ.erase freeIndex)
        q := by

  classical

  have hErase :
      Finset.sum
          (Finset.univ.erase freeIndex)
          q
        +
      q freeIndex
        =
      Finset.sum
        Finset.univ
        q := by

    exact
      Finset.sum_erase_add
        Finset.univ
        q
        (Finset.mem_univ freeIndex)

  have hTotal :
      Finset.sum
          Finset.univ
          q
        =
      1 := by

    simpa using hq.2

  rw [hTotal] at hErase

  linarith

/--
Abstract geometric form produced by the C++ box-simplex enumerator.

The point must be feasible, and there must exist one selected free
coordinate such that:

* every other coordinate is exactly at its lower or upper bound;
* the free coordinate is determined from the simplex equality.

Because feasibility is included, the computed free coordinate also lies
inside its interval.
-/
def BoxSimplexEnumeratorCandidate
    {d : ℕ}
    (lower upper : Fin d → ℝ)
    (q : ModeDistribution d) :
    Prop :=
  q ∈ ConfidencePolytope lower upper ∧
  ∃ freeIndex : Fin d,
    (
      ∀ k : Fin d,
        k ≠ freeIndex →
        OnIntervalEndpoint
          lower
          upper
          q
          k
    )
    ∧
    q freeIndex
      =
    1 -
      Finset.sum
        (Finset.univ.erase freeIndex)
        q

/--
Set of all feasible points having the geometry generated by the C++
enumerator.
-/
def BoxSimplexEnumeratorPoints
    {d : ℕ}
    (lower upper : Fin d → ℝ) :
    Set (ModeDistribution d) :=
  {
    q |
      BoxSimplexEnumeratorCandidate
        lower
        upper
        q
  }

/--
If the strictly-free coordinate set has cardinality at most one and contains
one strictly-free coordinate `freeIndex`, then every other coordinate is not
strictly free.
-/
theorem not_strictlyFree_of_ne_unique_free
    {d : ℕ}
    {lower upper : Fin d → ℝ}
    {q : ModeDistribution d}
    {freeIndex k : Fin d}
    (hCard :
      (strictlyFreeCoordinates
        lower
        upper
        q).card ≤ 1)
    (hFree :
      StrictlyFree
        lower
        upper
        q
        freeIndex)
    (hk :
      k ≠ freeIndex) :
    ¬ StrictlyFree
        lower
        upper
        q
        k := by

  intro hkFree

  have hFreeMem :
      freeIndex ∈
        strictlyFreeCoordinates
          lower
          upper
          q :=
    mem_strictlyFreeCoordinates.mpr
      hFree

  have hkMem :
      k ∈
        strictlyFreeCoordinates
          lower
          upper
          q :=
    mem_strictlyFreeCoordinates.mpr
      hkFree

  have hEq :
      freeIndex = k :=
    (Finset.card_le_one_iff.mp hCard)
      hFreeMem
      hkMem

  exact
    hk
      hEq.symm

/--
Every terminal confidence-polytope point has the geometry produced by the
C++ enumerator.

The dimension must be nonzero because the implementation chooses one
`freeIndex`. In the application `d = 4`.
-/
theorem terminalPoint_is_enumeratorCandidate
    {d : ℕ}
    {lower upper : Fin d → ℝ}
    {q : ModeDistribution d}
    (hd :
      0 < d)
    (hqTerminal :
      q ∈
        TerminalConfidencePoints
          lower
          upper) :
    BoxSimplexEnumeratorCandidate
      lower
      upper
      q := by

  classical

  rcases hqTerminal with
    ⟨hq, hAtMostOne⟩

  have hCard :
      (strictlyFreeCoordinates
        lower
        upper
        q).card ≤ 1 := by

    unfold AtMostOneStrictlyFree at hAtMostOne
    unfold strictlyFreeCount at hAtMostOne

    exact hAtMostOne

  by_cases hExistsFree :
      ∃ freeIndex : Fin d,
        StrictlyFree
          lower
          upper
          q
          freeIndex

  · rcases hExistsFree with
      ⟨freeIndex, hFree⟩

    refine
      ⟨hq, freeIndex, ?_, ?_⟩

    · intro k hk

      have hNotFree :
          ¬ StrictlyFree
              lower
              upper
              q
              k :=
        not_strictlyFree_of_ne_unique_free
          hCard
          hFree
          hk

      exact
        onIntervalEndpoint_of_not_strictlyFree
          hq
          hNotFree

    · exact
        probabilityVector_freeCoordinate_eq
          hq.1
          freeIndex

  · let freeIndex : Fin d :=
      ⟨0, hd⟩

    refine
      ⟨hq, freeIndex, ?_, ?_⟩

    · intro k hk

      have hNotFree :
          ¬ StrictlyFree
              lower
              upper
              q
              k := by

        intro hkFree

        exact
          hExistsFree
            ⟨k, hkFree⟩

      exact
        onIntervalEndpoint_of_not_strictlyFree
          hq
          hNotFree

    · exact
        probabilityVector_freeCoordinate_eq
          hq.1
          freeIndex

/--
Conversely, any feasible point with the C++ enumerator geometry has at most
one strictly-free coordinate.

Only the selected free coordinate can possibly be strictly interior.
-/
theorem enumeratorCandidate_is_terminalPoint
    {d : ℕ}
    {lower upper : Fin d → ℝ}
    {q : ModeDistribution d}
    (hCandidate :
      BoxSimplexEnumeratorCandidate
        lower
        upper
        q) :
    q ∈
      TerminalConfidencePoints
        lower
        upper := by

  classical

  rcases hCandidate with
    ⟨hq, freeIndex, hEndpoints, _hFreeValue⟩

  constructor

  · exact hq

  · unfold AtMostOneStrictlyFree
    unfold strictlyFreeCount

    have hSubset :
        strictlyFreeCoordinates
            lower
            upper
            q
          ⊆
        ({freeIndex} : Finset (Fin d)) := by

      intro k hk

      have hkFree :
          StrictlyFree
            lower
            upper
            q
            k :=
        mem_strictlyFreeCoordinates.mp
          hk

      by_cases hkEq :
          k = freeIndex

      · subst k
        simp

      · have hEndpoint :
            OnIntervalEndpoint
              lower
              upper
              q
              k :=
          hEndpoints
            k
            hkEq

        rcases hEndpoint with
          hLower | hUpper

        · exfalso

          exact
            (not_strictlyFree_of_eq_lower
              hLower)
              hkFree

        · exfalso

          exact
            (not_strictlyFree_of_eq_upper
              hUpper)
              hkFree

    have hCard :
        (strictlyFreeCoordinates
          lower
          upper
          q).card
          ≤
        ({freeIndex} : Finset (Fin d)).card :=
      Finset.card_le_card
        hSubset

    simpa using hCard

/--
For nonzero mode dimension, the terminal points from the convex-decomposition
proof are exactly the points having the C++ enumerator geometry.
-/
theorem terminalConfidencePoints_eq_enumeratorPoints
    {d : ℕ}
    (lower upper : Fin d → ℝ)
    (hd :
      0 < d) :
    TerminalConfidencePoints
        lower
        upper
      =
    BoxSimplexEnumeratorPoints
      lower
      upper := by

  ext q

  constructor

  · intro hq

    exact
      terminalPoint_is_enumeratorCandidate
        hd
        hq

  · intro hq

    exact
      enumeratorCandidate_is_terminalPoint
        hq

/--
The geometric candidate set corresponding to the C++ enumerator generates
the complete confidence polytope.
-/
theorem enumeratorPoints_generate_confidencePolytope
    {d : ℕ}
    (lower upper : Fin d → ℝ)
    (hd :
      0 < d)
    (hLower :
      ∀ i,
        0 ≤ lower i) :
    VerticesGenerateConfidencePolytope
      (BoxSimplexEnumeratorPoints
        lower
        upper)
      lower
      upper := by

  unfold VerticesGenerateConfidencePolytope

  have hTerminal :
      ConfidencePolytope
          lower
          upper
        ⊆
      convexHull ℝ
        (TerminalConfidencePoints
          lower
          upper) :=
    confidencePolytope_subset_convexHull_terminal
      lower
      upper
      hLower

  rw [
    terminalConfidencePoints_eq_enumeratorPoints
      lower
      upper
      hd
  ] at hTerminal

  exact hTerminal

end DROSafety.DRO
